#!/usr/bin/env python3
# Regenerate dash_gz.h from the uncompressed fallback page in dash_frontend.c.
# Run after editing the dashboard HTML/JS, then rebuild.
import re, gzip, codecs, sys, os

path = sys.argv[1] if len(sys.argv) > 1 else 'dash_frontend.c'
src = open(path).read()

# The editable page is the uncompressed fallback: starts right AFTER the
# http_setup("text/html") call (which is past the gzip branch) and runs to
# the next function. This excludes the gzip branch's header strings and the
# "text/html" arg, so only real page bytes are compressed.
s = src.find('http_setup(request, "text/html")')
s = src.find('\n', s) + 1
e = src.find('http_fn_api_dash', s)
body = src[s:e]

lits = re.findall(r'"((?:\\.|[^"\\])*)"', body)
page = ''.join(lits)
raw = codecs.decode(page.encode('utf-8'), 'unicode_escape').encode('latin-1', 'ignore')
gz = gzip.compress(raw, 9)

outdir = os.path.dirname(os.path.abspath(path))
with open(os.path.join(outdir, 'dash_gz.h'), 'w') as f:
    f.write('// Auto-generated by gen_dash_gz.py: gzip-compressed /dash page.\n')
    f.write('// Regenerate whenever you edit the dashboard, then rebuild.\n')
    f.write('#ifndef DASH_GZ_H\n#define DASH_GZ_H\n\n')
    f.write(f'// uncompressed {len(raw)} bytes -> gzip {len(gz)} bytes\n')
    f.write('static const unsigned char g_dashGz[] = {\n')
    for k in range(0, len(gz), 16):
        f.write('  ' + ','.join('0x%02x' % b for b in gz[k:k+16]) + ',\n')
    f.write('};\n')
    f.write(f'#define DASH_GZ_LEN {len(gz)}\n\n#endif\n')

print(f'page starts with: {raw[:60]!r}')
print(f'dash_gz.h written: {len(raw)} -> {len(gz)} bytes')
