/* ===========================================================================
   bms_frontend.c  --  JK-BMS live monitor HTML page served at /bms

   Adapted from jk-monitor.html (Web Bluetooth removed).
   The page polls /api_bms every 2 s; the ESP32 handles BLE transparently.
   =========================================================================== */

#include "bms_frontend.h"
#include "../httpserver/new_http.h"

int http_fn_serve_bms_html(http_request_t *request)
{
    http_setup(request, "text/html");

    /* ---- HEAD + CSS ---- */
    poststr(request,
        "<!DOCTYPE html><html lang='en'><head>"
        "<meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1,viewport-fit=cover'>"
        "<meta name='color-scheme' content='dark'>"
        "<title>JK-BMS \xc2\xb7 live monitor</title>"
        "<style>"
        ":root{"
          "--bg:#0b0e13;--panel:#11161e;--panel2:#171f2a;--line:#222d3b;"
          "--text:#e7eef6;--dim:#7c8a9a;--dim2:#566374;"
          "--charge:#37d67a;--discharge:#e8a317;--idle:#4aa3ff;--fault:#ef5350;"
          "--state:var(--idle);"
          "--mono:ui-monospace,'SF Mono','JetBrains Mono',Menlo,Consolas,monospace;"
          "--sans:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;"
        "}"
        "*{box-sizing:border-box}"
        "html,body{margin:0;background:var(--bg);color:var(--text);font-family:var(--sans)}"
        "body{padding:14px clamp(12px,4vw,22px) 30px;max-width:560px;margin:0 auto;-webkit-font-smoothing:antialiased}"
        ".bar{display:flex;align-items:center;gap:12px;margin:6px 0 16px}"
        ".id{display:flex;flex-direction:column;line-height:1.15}"
        ".id b{font-size:15px;letter-spacing:.14em;font-weight:700}"
        ".id span{font-size:11px;color:var(--dim2);letter-spacing:.18em;text-transform:uppercase}"
        ".dot{width:9px;height:9px;border-radius:50%;background:var(--state);flex:none}"
        ".streaming .dot{animation:pulse 1.6s ease-out infinite}"
        "@keyframes pulse{0%{box-shadow:0 0 0 0 color-mix(in srgb,var(--state) 60%,transparent)}"
          "70%{box-shadow:0 0 0 7px transparent}100%{box-shadow:0 0 0 0 transparent}}"
        ".spacer{flex:1}"
    );

    poststr(request,
        ".status{font-family:var(--mono);font-size:12.5px;color:var(--dim);"
          "background:var(--panel);border:1px solid var(--line);"
          "border-left:3px solid var(--state);border-radius:8px;"
          "padding:9px 12px;margin-bottom:18px;min-height:38px;"
          "display:flex;align-items:center;word-break:break-word}"
        ".gauge{position:relative;width:min(300px,80vw);aspect-ratio:1;margin:2px auto 24px}"
        ".gauge svg{width:100%;height:100%;transform:rotate(-90deg)}"
        ".gauge .track{fill:none;stroke:var(--panel2);stroke-width:13}"
        ".gauge .fill{fill:none;stroke:var(--state);stroke-width:13;stroke-linecap:round;"
          "transition:stroke-dashoffset .55s ease,stroke .3s}"
        ".gc{position:absolute;inset:0;display:flex;flex-direction:column;"
          "align-items:center;justify-content:center;text-align:center;padding:0 16%}"
        ".gc .soc{font-family:var(--mono);font-size:12px;color:var(--dim2);"
          "letter-spacing:.16em;margin-bottom:4px}"
        ".gc .volt{font-family:var(--mono);font-weight:700;"
          "font-size:clamp(30px,11vw,40px);line-height:1;color:var(--state)}"
        ".gc .volt .u{font-size:.42em;color:var(--dim);font-weight:500;margin-left:3px}"
        ".gc .amp{font-family:var(--mono);font-size:clamp(15px,5.5vw,19px);font-weight:600;margin-top:6px}"
        ".gc .sub{font-family:var(--mono);font-size:11.5px;color:var(--dim);margin-top:8px}"
        ".gc .cap{font-family:var(--mono);font-size:11.5px;color:var(--dim2);margin-top:3px}"
    );

    poststr(request,
        ".indicators{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:10px}"
        ".ind{background:var(--panel);border:1px solid var(--line);border-radius:11px;"
          "padding:13px 14px;display:flex;align-items:center;gap:10px}"
        ".ind .d2{width:9px;height:9px;border-radius:50%;background:var(--dim2);flex:none;transition:background .2s,box-shadow .2s}"
        ".ind .il{font-size:12px;color:var(--dim);letter-spacing:.06em;flex:1}"
        ".ind .is{font-family:var(--mono);font-size:13px;font-weight:700;color:var(--dim2)}"
        ".ind.on{border-color:color-mix(in srgb,var(--charge) 45%,var(--line))}"
        ".ind.on .d2{background:var(--charge);box-shadow:0 0 8px color-mix(in srgb,var(--charge) 70%,transparent)}"
        ".ind.on .is{color:var(--charge)}"
        ".balancer{background:var(--panel);border:1px solid var(--line);border-radius:11px;"
          "padding:13px 14px;margin-bottom:10px;transition:border-color .2s}"
        ".balancer.on{border-color:color-mix(in srgb,var(--charge) 45%,var(--line))}"
        ".bhead{display:flex;align-items:center;gap:10px;margin-bottom:11px}"
        ".bhead .d2{width:9px;height:9px;border-radius:50%;background:var(--dim2);flex:none;transition:background .2s,box-shadow .2s}"
        ".bhead .bt{font-size:12px;color:var(--dim);letter-spacing:.06em;flex:1}"
        ".bhead .bs{font-family:var(--mono);font-size:13px;font-weight:700;color:var(--dim2)}"
        ".balancer.on .d2{background:var(--charge);box-shadow:0 0 8px color-mix(in srgb,var(--charge) 70%,transparent)}"
        ".balancer.on .bs{color:var(--charge)}"
        ".bdata{display:grid;grid-template-columns:1fr 1fr;gap:10px}"
        ".bcell{background:var(--panel2);border-radius:8px;padding:9px 11px}"
        ".bcell .bk{font-size:10px;color:var(--dim2);letter-spacing:.12em;text-transform:uppercase}"
        ".bcell .bv{font-family:var(--mono);font-size:15px;font-weight:600;margin-top:4px}"
        ".temps{display:grid;grid-template-columns:1fr 1fr;gap:10px}"
        ".temps .t{background:var(--panel);border:1px solid var(--line);border-radius:11px;"
          "padding:11px 13px;display:flex;justify-content:space-between;align-items:baseline}"
        ".temps .t .k{font-size:11px;color:var(--dim2);letter-spacing:.12em;text-transform:uppercase}"
        ".temps .t .v{font-family:var(--mono);font-size:14px;font-weight:600}"
        "@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}"
        "</style></head><body>"
    );

    /* ---- HTML body ---- */
    poststr(request,
        "<div class='bar' id='bar'>"
          "<div class='dot'></div>"
          "<div class='id'><b>JK-BMS</b><span>live monitor</span></div>"
          "<div class='spacer'></div>"
        "</div>"
        "<div class='status' id='status'>Connecting to BMS via BLE\xe2\x80\xa6</div>"
        "<div class='gauge'>"
          "<svg viewBox='0 0 200 200'>"
            "<circle class='track' cx='100' cy='100' r='90'></circle>"
            "<circle class='fill'  cx='100' cy='100' r='90'></circle>"
          "</svg>"
          "<div class='gc'>"
            "<div class='soc' id='soc'>SOC \xe2\x80\x93\xe2\x80\x93%</div>"
            "<div class='volt'><span id='volt'>\xe2\x80\x93\xe2\x80\x93</span><span class='u'>V</span></div>"
            "<div class='amp' id='amp'>\xe2\x80\x93\xe2\x80\x93 A</div>"
            "<div class='sub' id='sub'>\xce\x94 \xe2\x80\x93\xe2\x80\x93 mV \xc2\xb7 \xe2\x80\x93\xe2\x80\x93 / \xe2\x80\x93\xe2\x80\x93 V</div>"
            "<div class='cap' id='cap'>\xe2\x80\x93\xe2\x80\x93 / \xe2\x80\x93\xe2\x80\x93 Ah</div>"
          "</div>"
        "</div>"
        "<div class='indicators'>"
          "<div class='ind' id='ind-chg'><span class='d2'></span><span class='il'>Charge</span><span class='is'>\xe2\x80\x93\xe2\x80\x93</span></div>"
          "<div class='ind' id='ind-dis'><span class='d2'></span><span class='il'>Discharge</span><span class='is'>\xe2\x80\x93\xe2\x80\x93</span></div>"
        "</div>"
        "<div class='balancer' id='balancer'>"
          "<div class='bhead'><span class='d2'></span><span class='bt'>Balancer</span><span class='bs' id='bal-state'>\xe2\x80\x93\xe2\x80\x93</span></div>"
          "<div class='bdata'>"
            "<div class='bcell'><div class='bk'>Current</div><div class='bv' id='balcur'>\xe2\x80\x93\xe2\x80\x93 A</div></div>"
            "<div class='bcell'><div class='bk'>Start voltage</div><div class='bv' id='bstart'>\xe2\x80\x93\xe2\x80\x93 V</div></div>"
          "</div>"
        "</div>"
        "<div class='temps'>"
          "<div class='t'><span class='k'>Battery</span><span class='v' id='tbatt'>\xe2\x80\x93\xe2\x80\x93</span></div>"
          "<div class='t'><span class='k'>MOSFET</span><span class='v'  id='tmos'>\xe2\x80\x93\xe2\x80\x93</span></div>"
        "</div>"
    );

    /* ---- JavaScript: polls /api_bms every 2 s ---- */
    poststr(request,
        "<script>"
        "'use strict';"
        "var bar=document.getElementById('bar');"
        "var fillEl=document.querySelector('.gauge .fill');"
        "var CIRC=2*Math.PI*90;"
        "fillEl.style.strokeDasharray=CIRC;"
        "fillEl.style.strokeDashoffset=CIRC;"
        "function $(id){return document.getElementById(id);}"
        "function setState(s){"
          "document.documentElement.style.setProperty('--state','var(--'+s+')');"
        "}"
        "function setStatus(msg,s){"
          "if(s)setState(s);"
          "$('status').textContent=msg;"
        "}"
        "function setInd(id,on){"
          "var el=$(id);el.classList.toggle('on',on);"
          "el.querySelector('.is').textContent=on?'ON':'OFF';"
        "}"
        "function fmt(x,dp){return x.toFixed(dp);}"
    );

    poststr(request,
        "function render(d){"
          "var st=d.a>0.05?'charge':(d.a<-0.05?'discharge':'idle');"
          "setState(st);"
          "bar.classList.add('streaming');"
          "var soc=Math.max(0,Math.min(100,d.soc));"
          "fillEl.style.strokeDashoffset=CIRC*(1-soc/100);"
          "$('soc').textContent='SOC '+d.soc+'%';"
          "$('volt').textContent=fmt(d.v,2);"
          "$('amp').textContent=(d.a>=0?'+':'')+fmt(d.a,2)+' A';"
          "$('sub').textContent='\u0394 '+d.dmv+' mV \u00b7 '+fmt(d.vmin,3)+' / '+fmt(d.vmax,3)+' V';"
          "$('cap').textContent=fmt(d.rem,1)+' / '+fmt(d.full,1)+' Ah';"
          "setInd('ind-chg',!!d.chg);"
          "setInd('ind-dis',!!d.dis);"
          "$('balancer').classList.toggle('on',!!d.bal);"
          "$('bal-state').textContent=d.bal?'ON':'OFF';"
          "$('balcur').textContent=fmt(d.balA,2)+' A';"
          "if(d.bstart>0)$('bstart').textContent=fmt(d.bstart,3)+' V';"
          "$('tbatt').textContent=fmt(d.t1,1)+' / '+fmt(d.t2,1)+' \u00b0C';"
          "$('tmos').textContent=fmt(d.tmos,1)+' \u00b0C';"
        "}"
    );

    poststr(request,
        "function poll(){"
          "fetch('/api_bms')"
            ".then(function(r){return r.json();})"
            ".then(function(d){"
              "if(!d.ok){setStatus('API error','fault');return;}"
              "if(!d.connected){"
                "bar.classList.remove('streaming');"
                "setState('idle');"
                "setStatus('ESP32 connecting to JK-BMS via BLE\u2026','idle');"
                "return;"
              "}"
              "render(d);"
              "setStatus('Live \u00b7 BLE connected \u00b7 C8:47:80:1A:18:B5','charge');"
            "})"
            ".catch(function(){"
              "setStatus('Cannot reach device \u2014 are you on the same Wi-Fi?','fault');"
            "});"
        "}"
        "poll();"
        "setInterval(poll,2000);"
        "</script></body></html>"
    );

    poststr(request, NULL);
    return 0;
}
