#include "dash_frontend.h"
#include "../new_common.h"  /* defines rtos_delay_milliseconds per platform */
#if !PLATFORM_ESPIDF
#include "rtos_pub.h"       /* Beken/BK7231 only — ESP32 uses vTaskDelay via new_common.h */
#endif
#include "dash_gz.h"  // pre-gzipped /dash page (g_dashGz / DASH_GZ_LEN)
#include <string.h>   // strstr

// Serves the dashboard page (HTML/CSS/JS) at /dash.
// Live data is fetched client-side from /api_dash (core/energy/bms/net/chginv),
// implemented in drv_bl_shared.c. iOS 5 Safari compatible: XHR + base64 binary
// (no fetch/color-mix/clamp/grid/aspect-ratio), -webkit-box flex fallbacks.

int http_fn_custom_dash(http_request_t *request) {
    // Serve the pre-gzipped dashboard when the client accepts gzip (every
    // browser, incl. iOS Safari, does). Regenerate dash_gz.h after edits.
    if (request->received != NULL && strstr(request->received, "gzip") != NULL) {
        poststr(request, "HTTP/1.1 200 OK\r\n");
        poststr(request, "Content-Type: text/html\r\n");
        poststr(request, "Content-Encoding: gzip\r\n");
        poststr(request, "Cache-Control: no-cache, no-store, must-revalidate\r\n");
        poststr(request, "Connection: close\r\n");
        poststr(request, "\r\n");
        postany(request, (const char*)g_dashGz, DASH_GZ_LEN);
        poststr(request, NULL);
        return 0;
    }
    http_setup(request, "text/html");

    // --- CSS part 1: shell, top-stats, columns ---
    poststr(request,
        "<!DOCTYPE html><html><head>"
        "<meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "<meta name='apple-mobile-web-app-capable' content='yes'>"
        "<meta name='apple-mobile-web-app-status-bar-style' content='black-translucent'>"
        "<title>My Dashboard</title>"
        "<style>"
        "html,body{height:100%;margin:0;background:#0b0b0b;overflow:hidden;}"
        "#night{position:fixed;top:0;left:0;right:0;bottom:0;background:#000;opacity:0;z-index:9999;pointer-events:none;-webkit-transition:opacity 1s;transition:opacity 1s;}"
        "#scaler{position:absolute;top:50%;left:50%;-webkit-transform-origin:center center;transform-origin:center center;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%);}"
        "#dash-container{width:1024px;background:#121212;padding:12px 14px 14px;-webkit-box-sizing:border-box;box-sizing:border-box;font-family:-apple-system,sans-serif;color:#eee;position:relative;border-radius:10px;}"
        ".top-stats{display:-webkit-box;-webkit-box-orient:horizontal;-webkit-box-align:center;-webkit-box-pack:justify;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;-webkit-align-items:center;align-items:center;background:#222;padding:12px 16px;border-radius:8px;text-align:center;width:100%;-webkit-box-sizing:border-box;box-sizing:border-box;white-space:nowrap;}"
        ".top-stats div{display:-webkit-box;-webkit-box-orient:vertical;-webkit-box-align:stretch;-webkit-box-pack:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:center;justify-content:center;margin:0 6px;}"
        ".top-stats label{color:#888;font-size:13px;text-transform:uppercase;margin-bottom:4px;display:block;}"
        ".top-stats b{font-size:28px;font-weight:600;}"
        "#d-va{color:#8a8a8a;}"
        ".c-exp{color:#4caf50;}.c-imp{color:#f44336;}"
        ".dash-row{display:-webkit-box;-webkit-box-orient:horizontal;-webkit-box-align:stretch;display:-webkit-flex;display:flex;margin-top:12px;-webkit-align-items:stretch;align-items:stretch;}"
        ".left-col{-webkit-box-flex:0;-webkit-flex:0 0 251px;flex:0 0 251px;width:251px;background:#222;padding:12px 14px;border-radius:8px;margin-right:14px;-webkit-box-sizing:border-box;box-sizing:border-box;}"
        ".center-col{-webkit-box-flex:1;-webkit-flex:1;flex:1;display:-webkit-box;-webkit-box-orient:vertical;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;min-width:0;}"
        ".right-col{-webkit-box-flex:0;-webkit-flex:0 0 214px;flex:0 0 214px;width:214px;margin-left:14px;display:-webkit-box;-webkit-box-orient:vertical;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-box-sizing:border-box;box-sizing:border-box;}"
    );
    rtos_delay_milliseconds(1);

    // --- CSS part 2: left table, graph, clock ---
    poststr(request,
        ".sep-lbl{font-size:12px;color:#888;text-transform:uppercase;letter-spacing:.5px;margin:0 0 8px;}"
        ".grp-lbl{font-size:12px;color:#888;text-transform:uppercase;letter-spacing:.5px;margin:18px 0 8px;}"
        ".reserved{height:46px;border:1px dashed #333;border-radius:6px;}"
        ".etbl{width:100%;border-collapse:collapse;font-size:14px;}"
        ".etbl th{font-size:11px;color:#888;font-weight:600;text-transform:uppercase;letter-spacing:.4px;padding:0 0 6px;border-bottom:1px solid #333;text-align:right;}"
        ".etbl th.nm{text-align:left;line-height:1.15;vertical-align:top;}"
        ".etbl td.nm{font-size:13px;font-weight:600;color:#6f757e;}"
        ".etbl td{padding:6px 0;border-bottom:1px solid #2c2c2c;color:#cfcfcf;}"
        ".etbl td.num{text-align:right;font-family:'Courier New',monospace;font-weight:bold;font-size:14px;width:58px;}"
        ".etbl td.exp,.etbl th.exh{padding-left:20px;}"
        ".etbl td.imp{color:#D97757;}.etbl td.exp{color:#37d67a;}"
        ".unit{font-size:10px;color:#666;}"
        ".etbl tr.tot td{border-bottom:none;border-top:1px solid #444;padding-top:8px;font-weight:bold;}"
        ".etbl tr.tot td.nm{color:#9aa0a8;text-transform:uppercase;font-size:13px;}"
        ".etbl tr.tot td.num{font-size:12px;}"
        ".leg-h{display:-webkit-box;-webkit-box-orient:horizontal;-webkit-box-pack:center;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;-webkit-align-items:center;align-items:center;margin-top:10px;font:12px sans-serif;color:#aaa;}"
        ".leg-i{display:-webkit-box;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-align-items:center;align-items:center;margin:0 14px;}"
        ".leg-sw{display:inline-block;width:18px;height:4px;margin-right:8px;}"
        ".graph-col{-webkit-box-flex:0;-webkit-flex:0 0 auto;flex:0 0 auto;background:#222;padding:15px;border-radius:8px;display:-webkit-box;-webkit-box-orient:horizontal;-webkit-box-align:center;-webkit-box-pack:center;display:-webkit-flex;display:flex;-webkit-align-items:center;align-items:center;-webkit-justify-content:center;justify-content:center;-webkit-box-sizing:border-box;box-sizing:border-box;overflow:hidden;}"
        "canvas{width:100%;max-width:592px;height:auto;display:block;margin:0 auto;}"
        ".clk-row{-webkit-box-flex:1;-webkit-flex:1;flex:1;background:#222;border-radius:8px;padding:6px 12px;margin-top:14px;display:-webkit-box;-webkit-box-orient:vertical;-webkit-box-align:center;-webkit-box-pack:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-align-items:center;align-items:center;-webkit-justify-content:center;justify-content:center;-webkit-box-sizing:border-box;box-sizing:border-box;}"
        ".clk-text{display:-webkit-box;-webkit-box-orient:horizontal;-webkit-box-align:baseline;-webkit-box-pack:center;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-align-items:baseline;align-items:baseline;-webkit-justify-content:center;justify-content:center;margin-top:6px;font-size:19px;color:#ccc;}"
        ".clk-text #d-day{font-weight:bold;color:#aaa;}"
        ".clk-text #d-date{margin-left:9px;color:#aaa;}"
        "#d-clk{font-size:144px;font-weight:bold;color:#09F;font-family:monospace;line-height:1;letter-spacing:-6px;}"
        "#d-day{font-size:20px;font-weight:600;color:#eee;text-transform:uppercase;letter-spacing:1px;}"
        "#d-date{font-size:14px;color:#888;}"
        ".close-btn{display:none;}"
    );
    rtos_delay_milliseconds(1);

    // --- CSS part 3: battery gauge + tempblock ---
    poststr(request,
        ".batt{background:#11161e;border:1px solid #222d3b;border-radius:8px;padding:10px 10px 12px;position:relative;}"
        ".bat-gear{position:absolute;top:33px;right:8px;width:30px;height:30px;background:#2a2d31;border:none;border-radius:6px;cursor:pointer;display:-webkit-box;-webkit-box-pack:center;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;-webkit-align-items:center;align-items:center;z-index:6;}"
        ".bat-gear svg{width:17px;height:17px;stroke:#cfd6dd;}"
        ".cd-side{position:absolute;bottom:4px;}"
        ".cd-l{left:2px;}"
        ".cd-r{right:2px;}"
        ".bat-pop{position:absolute;left:10px;right:10px;top:67px;background:#0c1118;border:1px solid #2a3a4d;border-radius:8px;padding:10px 12px 4px;z-index:7;-webkit-box-sizing:border-box;box-sizing:border-box;}"
        ".batt-head{text-align:center;margin-bottom:6px;}"
        ".batt-head h1{font-size:13px;font-weight:700;color:#e7eef6;font-family:'Courier New',monospace;letter-spacing:.5px;margin:0;}"
        ".gauge{position:relative;width:188px;height:188px;margin:0 auto 8px;}"
        ".gauge svg{width:188px;height:188px;}"
        ".gauge .track{fill:none;stroke:#171f2a;stroke-width:11;}"
        ".gauge .fill{fill:none;stroke:#37d67a;stroke-width:11;stroke-linecap:round;}"
        ".gc{position:absolute;top:0;left:0;right:0;bottom:0;display:-webkit-box;-webkit-box-orient:vertical;-webkit-box-align:center;-webkit-box-pack:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-align-items:center;align-items:center;-webkit-justify-content:center;justify-content:center;text-align:center;padding:0 12%;}"
        ".gc .power{font-family:'Courier New',monospace;font-size:10px;color:#7c8a9a;}"
        ".gc .bigsoc{font-family:'Courier New',monospace;font-weight:700;font-size:36px;line-height:1;color:#37d67a;}"
        ".gc .bigsoc .pct{font-size:17px;font-weight:600;}"
        ".gc .state-lbl{font-size:10px;font-weight:600;color:#37d67a;margin-top:1px;}"
        ".gc .av{display:-webkit-box;-webkit-box-pack:center;-webkit-box-align:baseline;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;-webkit-align-items:baseline;align-items:baseline;font-family:'Courier New',monospace;font-size:11px;font-weight:600;margin-top:3px;}"
        ".gc .av span{margin:0 4px;}"
        ".gc .cap{font-family:'Courier New',monospace;font-size:10px;font-weight:600;margin-top:1px;}"
        ".gc .cells{font-family:'Courier New',monospace;font-size:9px;color:#7c8a9a;margin-top:4px;}"
        ".gc .delta{font-family:'Courier New',monospace;font-size:9px;color:#7c8a9a;margin-top:1px;}"
        ".gc .rule{width:80%;height:1px;background:#222d3b;margin:5px 0;}"
        ".gc .u{color:#7c8a9a;font-weight:500;}"
        ".tempblock{margin-top:8px;}"
        ".trow{display:-webkit-box;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-align-items:center;align-items:center;font-size:12px;padding:3px 2px;}"
        ".trow .ic{width:15px;height:15px;margin-right:6px;}"
        ".trow .lbl{color:#7c8a9a;min-width:60px;font-weight:bold;}"
        ".trow .val{color:#e7eef6;font-weight:bold;font-family:'Courier New',monospace;white-space:nowrap;}"
        ".trow.bon .val{color:#37d67a;}"
        ".tbrule{height:1px;background:#222d3b;margin:3px 0;}"
        ".cdrow{display:-webkit-box;-webkit-box-pack:center;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;-webkit-align-items:center;align-items:center;padding:4px 1px 2px;}"
        ".cd-item{display:-webkit-box;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-align-items:center;align-items:center;margin:0 12px;}"
        ".cd-item .ic{width:15px;height:15px;opacity:.28;margin-right:5px;}"
        ".cd-item.on .ic{opacity:1;}"
        ".cd-item .dot2{width:8px;height:8px;border-radius:50%;background:#2a3340;}"
        ".cd-item.on .dot2{background:#4aa3ff;}"
        ".ic-bolt{fill:#f2b84b;}.ic-batt{stroke:#37d67a;}.ic-batt .lvl{fill:#37d67a;stroke:none;}"
        ".ic-dis{stroke:#4aa3ff;}.ic-dis .lvl{fill:#4aa3ff;stroke:none;}"
        ".ic-thermo{stroke:#ef6a6a;}.ic-scale{stroke:#9aa7b5;}"
        ".sns-gear{background:none;border:none;padding:2px;cursor:pointer;line-height:0;}"
        ".sns-gear svg{width:14px;height:14px;stroke:#888;fill:none;}"
        ".sns-pop{position:absolute;top:14px;left:50%;width:440px;margin-left:-220px;background:#15181d;border:1px solid #3a3d42;border-radius:10px;z-index:50;overflow:hidden;-webkit-box-sizing:border-box;box-sizing:border-box;}"
        ".cfg-sec{font-size:9px;font-weight:700;color:#555;text-transform:uppercase;letter-spacing:.7px;padding:8px 12px 5px;border-bottom:1px solid #1e242d;margin-top:2px;}"
        ".cfg-field{display:-webkit-box;-webkit-box-orient:horizontal;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-align-items:center;align-items:center;padding:6px 12px;}"
        ".cfg-field label{-webkit-box-flex:1;-webkit-flex:1;flex:1;font-size:11px;color:#7c8a9a;font-weight:500;padding-right:8px;}"
        ".tbl-wrap{padding:0 12px;}"
        ".tbl-wrap table{width:100%;border-collapse:collapse;}"
        ".col-hdr{font-size:9px;font-weight:700;color:#444;text-transform:uppercase;letter-spacing:.6px;padding:6px 0 3px;text-align:left;border-bottom:1px solid #1e242d;}"
        ".irow{display:-webkit-box;-webkit-box-orient:horizontal;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-align-items:center;align-items:center;padding:6px 0;}"
        ".irow label{-webkit-box-flex:1;-webkit-flex:1;flex:1;font-size:11px;color:#7c8a9a;font-weight:500;display:-webkit-box;-webkit-box-orient:horizontal;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-align-items:center;align-items:center;padding-right:6px;}"
        ".sblk{padding:5px 0 6px;}"
        ".sblk .slbl{font-size:10px;color:#666;text-transform:uppercase;letter-spacing:.4px;}"
        ".sblk .sval{font-size:11px;color:#aaa;margin:2px 0 3px;}"
        ".sblk .sval span{color:#e7eef6;font-weight:bold;}"
        ".sblk input{width:100%;-webkit-box-sizing:border-box;box-sizing:border-box;}"
        ".cfg-sld-b{padding:3px 12px 10px;}"
        ".cfg-sld-b label{display:block;font-size:10px;color:#666;margin-bottom:4px;text-transform:uppercase;letter-spacing:.5px;}"
        ".cfg-sld-b input{width:100%;-webkit-box-sizing:border-box;box-sizing:border-box;}"
        ".cfg-foot{display:-webkit-box;-webkit-box-orient:horizontal;display:-webkit-flex;display:flex;padding:9px 12px 11px;border-top:1px solid #222d3b;margin-top:4px;}"
        ".cfg-ret{-webkit-box-flex:1;-webkit-flex:1;flex:1;background:#2a2d31;border:none;color:#9aa0a8;border-radius:6px;padding:8px 0;font-size:11px;font-weight:700;cursor:pointer;text-transform:uppercase;letter-spacing:.3px;font-family:-apple-system,sans-serif;text-align:center;margin-right:8px;}"
        ".cfg-sv{-webkit-box-flex:2;-webkit-flex:2;flex:2;background:#09F;border:none;color:#fff;border-radius:6px;padding:8px 0;font-size:12px;font-weight:700;cursor:pointer;text-transform:uppercase;letter-spacing:.3px;font-family:-apple-system,sans-serif;text-align:center;}"
    );
    rtos_delay_milliseconds(1);

    // --- CSS part 4: button box + sliders ---
    poststr(request,
        ".btn-box{-webkit-box-flex:1;-webkit-flex:1;flex:1;background:#222;border-radius:8px;padding:14px;margin-top:14px;position:relative;-webkit-box-sizing:border-box;box-sizing:border-box;display:-webkit-box;-webkit-box-orient:vertical;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;}"
        ".btn-grid{-webkit-box-flex:1;-webkit-flex:1;flex:1;display:-webkit-box;-webkit-box-orient:horizontal;-webkit-box-align:stretch;display:-webkit-flex;display:flex;-webkit-align-items:stretch;align-items:stretch;min-height:120px;}"
        ".btn{border:none;color:#fff;border-radius:6px;font-weight:bold;cursor:pointer;overflow:hidden;font-family:-apple-system,sans-serif;text-align:center;display:-webkit-box;-webkit-box-orient:vertical;-webkit-box-pack:center;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;-webkit-justify-content:center;justify-content:center;-webkit-align-items:center;align-items:center;-webkit-box-sizing:border-box;box-sizing:border-box;}"
        ".bic{display:block;height:22px;margin-bottom:3px;text-align:center;}"
        ".bic svg{width:22px;height:22px;stroke:currentColor;fill:none;display:block;margin:0 auto;}"
        ".btxt{display:block;font-size:13px;line-height:1;white-space:nowrap;text-align:center;}"
        ".btn-left{-webkit-box-flex:1;-webkit-flex:1;flex:1;margin-right:8px;display:-webkit-box;-webkit-box-orient:vertical;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;}"
        ".btn-right{-webkit-box-flex:1;-webkit-flex:1;flex:1;display:-webkit-box;-webkit-box-orient:vertical;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;}"
        ".btn-auto{-webkit-box-flex:2;-webkit-flex:2;flex:2;margin-bottom:8px;background:#09F;}"
        ".btn-auto .btxt{font-size:15px;}"
        ".btn-gear{-webkit-box-flex:2;-webkit-flex:2;flex:2;background:#3a3d42;}"
        ".btn-gear svg{width:20px;height:20px;stroke:#cfd6dd;}"
        ".btn-third{-webkit-box-flex:1;-webkit-flex:1;flex:1;background:#555;margin-bottom:8px;}"
        ".btn-div{-webkit-box-flex:1.35;-webkit-flex:1.35;flex:1.35;background:#555;-webkit-box-orient:horizontal;-webkit-box-direction:normal;-webkit-flex-direction:row;flex-direction:row;}"
        ".btn-div .bic{height:auto;margin-bottom:0;margin-right:6px;display:inline-block;}"
        ".btn-div .bic svg{display:inline;margin:0;vertical-align:middle;}"
        ".btn-third.last,.btn-div.last{margin-bottom:0;}"
        ".inv-pair{-webkit-box-flex:1;-webkit-flex:1;flex:1;display:-webkit-box;-webkit-box-orient:horizontal;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;margin-bottom:8px;}"
        ".inv-pair .btn{-webkit-box-flex:1;-webkit-flex:1;flex:1;}"
        ".inv-pair .btn:first-child{margin-right:4px;}"
        ".t-inp{background:#1e2530;border:1px solid #3a4452;-webkit-border-radius:4px;border-radius:4px;color:#e7eef6;font-size:12px;padding:3px 5px;-webkit-box-sizing:border-box;box-sizing:border-box;font-family:'Courier New',monospace;}"
        ".ip-block{margin-bottom:10px;}"
        ".ip-block label{display:block;font-size:11px;color:#aaa;margin-bottom:4px;text-transform:uppercase;letter-spacing:.5px;}"
        ".ip-block .t-inp{width:64px;}"
        ".tmr{display:none;width:13px;height:13px;margin-right:6px;}"
        ".tmr.show{display:-webkit-inline-box;display:inline-block;}"
        ".cfg-pop{position:absolute;left:14px;right:14px;bottom:0;background:#15181d;border:1px solid #3a3d42;border-radius:8px;padding:10px 12px 2px;z-index:30;-webkit-box-sizing:border-box;box-sizing:border-box;}"
        ".cfg-head{display:-webkit-box;-webkit-box-pack:justify;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;-webkit-align-items:center;align-items:center;margin-bottom:10px;font-size:11px;letter-spacing:.5px;text-transform:uppercase;color:#888;}"
        ".cfg-x{cursor:pointer;color:#cfd6dd;font-size:16px;line-height:1;padding:2px 6px;-webkit-border-radius:4px;border-radius:4px;background:#2a2d31;}"
        ".sld-block{margin-bottom:12px;}"
        ".sld-block label{display:block;font-size:11px;color:#aaa;margin-bottom:5px;text-transform:uppercase;letter-spacing:.5px;}"
        ".sld-block input{width:100%;-webkit-box-sizing:border-box;box-sizing:border-box;}"
        "</style></head><body>"
    );
    rtos_delay_milliseconds(1);

    // --- Layout: top stats ---
    poststr(request,
        "<div id='night'></div>"
        "<div id='scaler'><div id='dash-container'>"
        "<div class='top-stats'>"
        "<div><label>Voltage &amp; Current</label><b id='d-va'>--</b></div>"
        "<div><label>Power</label><b id='d-pwr'>--</b></div>"
        "<div><label>Now / 15min Est.</label><b><span id='d-bal'>--</span> / <span id='d-est'>--</span></b></div>"
        "<div id='d-chg-box'><label id='c-lbl'>ESS Status:</label><b id='c-v'>--</b><span id='c-chg' style='display:block;font-size:14px;color:#4caf50;margin-top:4px;'></span></div>"
        "</div>"
        "<div class='dash-row'>"
    );
    rtos_delay_milliseconds(1);

    // --- Layout: left column (reserved + import/export table + legend) ---
    poststr(request,
        "<div class='left-col'>"
        "<div style='display:-webkit-box;-webkit-box-pack:justify;-webkit-box-align:center;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;-webkit-align-items:center;align-items:center;margin:0 0 8px;'>"
        "<span class='sep-lbl' style='margin:0;'>Sensor Data</span>"
        "<button class='sns-gear' onclick='toggleSnsCfg()'><svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='3'></circle><path d='M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z'></path></svg></button>"
        "</div>"
        "<div id='sns-pop' class='sns-pop' style='display:none;'>"
        "<div class='cfg-head'><span>System Configuration</span><span class='cfg-x' onclick='toggleSnsCfg()'>&#x2715;</span></div>"
        "<div class='cfg-sec'>BMS Devices</div>"
        "<div class='cfg-field'><label>BMS 1 MAC</label><input class='t-inp' type='text' id='bms1-mac' maxlength='17' placeholder='AA:BB:CC:DD:EE:FF' oninput='fmtMac(this)' style='width:150px;letter-spacing:1px;'></div>"
        "<div class='cfg-field'><label>BMS 2 MAC</label><input class='t-inp' type='text' id='bms2-mac' maxlength='17' placeholder='AA:BB:CC:DD:EE:FF' oninput='fmtMac(this)' style='width:150px;letter-spacing:1px;'></div>"
        "<div class='cfg-sec'>Meter IP Addresses</div>"
        "<div class='tbl-wrap'><table>"
        "<tr><th class='col-hdr' style='padding-right:16px;width:50%;'>Consumption</th><th class='col-hdr' style='width:50%;'>Generation</th></tr>"
        "<tr>"
        "<td style='padding-right:16px;'><div class='irow'><label><svg width='11' height='11' viewBox='0 0 24 24' fill='#f2b84b' style='margin-right:5px;vertical-align:middle;'><path d='M13 2 3 14h7l-1 8 10-12h-7z'/></svg>L1</label><input class='t-inp' type='text' id='m1-ip' maxlength='3' placeholder='...' style='width:40px;text-align:center;'></div></td>"
        "<td><div class='irow'><label><svg width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='#f2b84b' stroke-width='2.5' stroke-linecap='round' style='margin-right:5px;vertical-align:middle;'><circle cx='12' cy='12' r='4'/><line x1='12' y1='2' x2='12' y2='6'/><line x1='12' y1='18' x2='12' y2='22'/><line x1='4.93' y1='4.93' x2='7.76' y2='7.76'/><line x1='16.24' y1='16.24' x2='19.07' y2='19.07'/><line x1='2' y1='12' x2='6' y2='12'/><line x1='18' y1='12' x2='22' y2='12'/><line x1='4.93' y1='19.07' x2='7.76' y2='16.24'/><line x1='16.24' y1='7.76' x2='19.07' y2='4.93'/></svg>Solar</label><input class='t-inp' type='text' id='m4-ip' maxlength='3' placeholder='...' style='width:40px;text-align:center;'></div></td>"
        "</tr><tr>"
        "<td style='padding-right:16px;border-top:1px solid #1e242d;'><div class='irow'><label><svg width='11' height='11' viewBox='0 0 24 24' fill='#f2b84b' style='margin-right:5px;vertical-align:middle;'><path d='M13 2 3 14h7l-1 8 10-12h-7z'/></svg>L2</label><input class='t-inp' type='text' id='m2-ip' maxlength='3' placeholder='...' style='width:40px;text-align:center;'></div></td>"
        "<td style='border-top:1px solid #1e242d;'><div class='irow'><label><svg width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='#f2b84b' stroke-width='2.5' stroke-linecap='round' style='margin-right:5px;vertical-align:middle;'><circle cx='12' cy='12' r='4'/><line x1='12' y1='2' x2='12' y2='6'/><line x1='12' y1='18' x2='12' y2='22'/><line x1='4.93' y1='4.93' x2='7.76' y2='7.76'/><line x1='16.24' y1='16.24' x2='19.07' y2='19.07'/><line x1='2' y1='12' x2='6' y2='12'/><line x1='18' y1='12' x2='22' y2='12'/><line x1='4.93' y1='19.07' x2='7.76' y2='16.24'/><line x1='16.24' y1='7.76' x2='19.07' y2='4.93'/></svg>Solar</label><input class='t-inp' type='text' id='m5-ip' maxlength='3' placeholder='...' style='width:40px;text-align:center;'></div></td>"
        "</tr><tr>"
        "<td style='padding-right:16px;border-top:1px solid #1e242d;'><div class='irow'><label><svg width='11' height='11' viewBox='0 0 24 24' fill='#f2b84b' style='margin-right:5px;vertical-align:middle;'><path d='M13 2 3 14h7l-1 8 10-12h-7z'/></svg>L3</label><input class='t-inp' type='text' id='m3-ip' maxlength='3' placeholder='...' style='width:40px;text-align:center;'></div></td>"
        "<td style='border-top:1px solid #1e242d;'><div class='irow'><label><svg width='14' height='11' viewBox='0 0 24 24' fill='none' stroke='#37d67a' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' style='margin-right:5px;vertical-align:middle;'><rect x='2' y='7.5' width='16' height='9' rx='2'/><path d='M21 11v2'/></svg>ESS Inverter</label><input class='t-inp' type='text' id='m6-ip' maxlength='3' placeholder='...' style='width:40px;text-align:center;'></div></td>"
        "</tr></table></div>"
        "<div class='cfg-sec'>Remote Equipment</div>"
        "<div class='tbl-wrap'><table>"
        "<tr>"
        "<td style='padding-right:16px;width:50%;'><div class='irow'><label>Boost Inverter</label><input class='t-inp' type='text' id='inv2-ip' maxlength='3' placeholder='...' style='width:40px;text-align:center;'></div></td>"
        "<td style='width:50%;'><div class='irow'><label>Diversion Load</label><input class='t-inp' type='text' id='byp-ip' maxlength='3' placeholder='...' style='width:40px;text-align:center;'></div></td>"
        "</tr><tr>"
        "<td style='padding-right:16px;border-top:1px solid #1e242d;vertical-align:top;'><div class='sblk'><div class='slbl'>Net energy trigger</div><div class='sval'><span id='lbl-boost'>10</span> Wh</div><input type='range' id='sld-boost' min='10' max='50' value='10' oninput='document.getElementById(\"lbl-boost\").innerHTML=this.value'></div></td>"
        "<td style='border-top:1px solid #1e242d;vertical-align:top;'><div class='sblk'><div class='slbl'>Net energy trigger</div><div class='sval'><span id='cfg-lbl-div'>-60</span> Wh</div><input type='range' id='cfg-sld-div' min='30' max='200' value='60' oninput='var e=document.getElementById(\"cfg-lbl-div\");if(e)e.innerHTML=\"-\"+this.value'></div></td>"
        "</tr></table></div>"
        "<div class='cfg-foot'><button class='cfg-ret' id='cfg-ret-btn' onclick='doCfgRetrieve()'>&#x21d3; Retrieve</button><button class='cfg-sv' id='cfg-sv-btn' onclick='doCfgSave()'>Save</button></div>"
        "</div>"
        "<div class='reserved'></div>"
        "<table class='etbl' style='margin-top:14px;'>"
        "<tr><th class='nm'>Energy<br><span class='unit'>details</span></th><th>Import <span class='unit'>kWh</span></th><th class='exh'>Export <span class='unit'>kWh</span></th></tr>"
        "<tr><td class='nm'>Last Hour</td><td class='num imp' id='d-clh-i'>--</td><td class='num exp' id='d-clh-e'>--</td></tr>"
        "<tr><td class='nm'>Today</td><td class='num imp' id='d-ctoday-i'>--</td><td class='num exp' id='d-ctoday-e'>--</td></tr>"
        "<tr><td class='nm'>Yesterday</td><td class='num imp' id='d-cyest-i'>--</td><td class='num exp' id='d-cyest-e'>--</td></tr>"
        "<tr><td class='nm'>2 Days Ago</td><td class='num imp' id='d-c2d-i'>--</td><td class='num exp' id='d-c2d-e'>--</td></tr>"
        "<tr><td class='nm'>3 Days Ago</td><td class='num imp' id='d-c3d-i'>--</td><td class='num exp' id='d-c3d-e'>--</td></tr>"
        "<tr class='tot'><td class='nm'>Total</td><td class='num imp' id='d-tot-i'>--</td><td class='num exp' id='d-tot-e'>--</td></tr>"
        "</table>"
        "</div>"
    );
    rtos_delay_milliseconds(1);

    // --- Layout: center column (graph + clock) ---
    poststr(request,
        "<div class='center-col'>"
        "<div class='graph-col' id='graph-col'>"
        "<div style='width:100%;max-width:592px;margin:0 auto;'>"
        "<div style='position:relative;width:100%;padding-bottom:57.43%;'>"
        "<canvas id='dynCanvas' style='position:absolute;top:0;left:0;width:100%;height:100%;'></canvas>"
        "</div></div></div>"
        "<div class='leg-h' id='leg-h'>"
        "<span class='leg-i'><span class='leg-sw' style='background:#aaa;'></span>Total Energy</span>"
        "<span class='leg-i'><span class='leg-sw' style='background:#4caf50;'></span>Charger Avg</span>"
        "<span class='leg-i'><span class='leg-sw' style='background:#ff9800;'></span>Inverter Avg</span>"
        "</div>"
        "<div class='clk-row'>"
        "<div id='d-clk'>--:--</div>"
        "<div class='clk-text'><div id='d-day'>--</div><div id='d-date'>--</div></div>"
        "</div>"
        "</div>"
    );
    rtos_delay_milliseconds(1);

    // --- Layout: right column (battery gauge) ---
    poststr(request,
        "<div class='right-col'>"
        "<div class='batt' id='batt-panel'>"
        "<div class='batt-head'><h1 id='bt-title'>--</h1></div>"
        "<button class='bat-gear' id='bat-gear-btn' onclick='toggleBatCfg()'><svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='3'></circle><path d='M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z'></path></svg></button>"
        "<div id='bat-pop' class='bat-pop' style='display:none;'>"
        "<div class='cfg-head'><span>Cut-off Voltage</span><span class='cfg-x' onclick='toggleBatCfg()'>&#x2715;</span></div>"
        "<div class='sld-block'><label>Charger cut (<span id='lbl-cv'>4.00</span> V)</label><input type='range' id='sld-cv' min='360' max='400' value='400' oninput='bvIn(\"cv\",this.value)' onchange='s_cv(this.value)'></div>"
        "<div class='sld-block'><label>Inverter cut (<span id='lbl-iv'>3.30</span> V)</label><input type='range' id='sld-iv' min='330' max='380' value='330' oninput='bvIn(\"iv\",this.value)' onchange='s_iv(this.value)'></div>"
        "</div>"
        "<div class='gauge'>"
        "<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'>"
        "<circle class='track' cx='100' cy='100' r='90'></circle>"
        "<circle class='fill' id='gaugeFill' cx='100' cy='100' r='90' transform='rotate(-90 100 100)'></circle>"
        "</svg>"
        "<div class='gc'>"
        "<div class='power'><span id='bt-pwr'>--</span> <span class='u'>W</span></div>"
        "<div class='bigsoc'><span id='bt-soc'>--</span><span class='pct' id='bt-pct'>%</span></div>"
        "<div class='rule'></div>"
        "<div class='state-lbl' id='bt-state'>--</div>"
        "<div class='av'><span><span id='bt-a'>--</span> <span class='u'>A</span></span><span><span id='bt-v'>--</span> <span class='u'>V</span></span></div>"
        "<div class='rule'></div>"
        "<div class='cap'><b id='bt-cap'>--</b> <span class='u'>/ <span id='bt-capf'>--</span> Ah</span></div>"
        "<div class='cells'><span id='bt-cells'>-- - --</span> V</div>"
        "<div class='delta'>&#916; <span id='bt-delta'>--</span> mV</div>"
        "</div>"
        "<div class='cd-side cd-l'><div class='cd-item' id='bt-chg'><svg class='ic ic-bolt' viewBox='0 0 24 24'><path d='M13 2 3 14h7l-1 8 10-12h-7z'/></svg><span class='dot2'></span></div></div>"
        "<div class='cd-side cd-r'><div class='cd-item' id='bt-dis'><svg class='ic ic-dis' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M9 18h6'/><path d='M10 22h4'/><path d='M15.1 14c.2-1 .7-1.8 1.4-2.5A4.65 4.65 0 0 0 18 8 6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.2 1.5 1.4 2.5'/></svg><span class='dot2'></span></div></div>"
        "</div>"
    );
    rtos_delay_milliseconds(1);

    // --- Layout: battery tempblock ---
    poststr(request,
        "<div class='tempblock'>"
        "<div class='trow'>"
        "<svg class='ic ic-thermo' viewBox='0 0 24 24' fill='none' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M14 14.76V5a2 2 0 1 0-4 0v9.76a4 4 0 1 0 4 0z'/></svg>"
        "<span class='lbl'>Battery:</span><span class='val'><span id='bt-tbat'>--</span> <span class='u'>&#176;C</span></span>"
        "</div>"
        "<div class='trow'>"
        "<svg class='ic ic-thermo' viewBox='0 0 24 24' fill='none' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M14 14.76V5a2 2 0 1 0-4 0v9.76a4 4 0 1 0 4 0z'/></svg>"
        "<span class='lbl'>Mosfet:</span><span class='val'><span id='bt-tmos'>--</span> <span class='u'>&#176;C</span></span>"
        "</div>"
        "<div class='tbrule'></div>"
        "<div class='trow' id='bt-balrow'>"
        "<svg class='ic ic-scale' viewBox='0 0 24 24' fill='none' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z'/><path d='m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z'/><path d='M7 21h10M12 3v18M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2'/></svg>"
        "<span class='lbl'>Balancer:</span><span class='val'><span id='bt-bal'>--</span> <span class='u'>A</span></span>"
        "</div>"
        "</div>"
        "</div>"
    );
    rtos_delay_milliseconds(1);

    // --- Layout: button box (AUTO tall + INV/CHG halves, Diversion, sliders) ---
    poststr(request,
        "<div class='btn-box'>"
        "<div class='sep-lbl'>ESS System Modes</div>"
        "<div class='btn-grid'>"
        "<div class='btn-left'>"
        "<button id='m-btn' class='btn btn-auto' onclick='tm()'>"
        "<span class='bic' id='m-ic'></span>"
        "<span class='btxt' id='m-txt'>--</span></button>"
        "<button id='gear-btn' class='btn btn-gear' onclick='toggleCfg()'>"
        "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='3'></circle><path d='M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z'></path></svg></button>"
        "</div>"
        "<div class='btn-right'>"
        "<div class='inv-pair'>"
        "<button id='inv1-btn' class='btn btn-third' onclick='t_inv1()'><span class='btxt'>INV1</span></button>"
        "<button id='inv2-btn' class='btn btn-third' onclick='t_inv2()'><span class='btxt'>INV2</span></button>"
        "</div>"
        "<button id='chg-btn' class='btn btn-third' onclick='t_chg()'><span class='btxt'>CHARGER</span></button>"
        "<button id='div-btn' class='btn btn-div last' onclick='td()'>"
        "<span class='bic' id='div-ic'></span>"
        "<span class='btxt'>DIVERSION</span></button>"
        "</div>"
        "</div>"
        "<div id='cfg-pop' class='cfg-pop' style='display:none;'>"
        "<div class='cfg-head'><span>Settings</span><span class='cfg-x' onclick='toggleCfg()'>&#x2715;</span></div>"
        "<div class='sld-block'><label>Max Pwr (<span id='lbl-pwr'></span>%)</label>"
        "<input type='range' id='sld-pwr' min='18' max='100' value='100' oninput='sIn(\"pwr\",this.value)' onchange='s_pwr(this.value)'></div>"
        "<div class='sld-block'><label>Export (<span id='lbl-exp'></span> Wh)</label>"
        "<input type='range' id='sld-exp' min='10' max='100' value='20' oninput='sIn(\"exp\",this.value)' onchange='s_exp(this.value)'></div>"
        "</div>"
        "</div>"   // btn-box
        "</div>"   // right-col
        "</div>"   // dash-row
        "</div>"   // dash-container
        "</div>"   // scaler
    );
    rtos_delay_milliseconds(1);

    // --- JS part 1: vars, helpers, decoders ---
    poststr(request,
        "<script>"
        "var busy=false,busySince=0,lastEv=-1,lastEnergyT=0,lastGraphT=0,graphIdx=0,lastClk='';"
        "function z48(){var a=[],i;for(i=0;i<48;i++)a[i]=0;return a;}"
        "var state_import=z48(),state_export=z48(),state_chg=z48(),state_inv=z48();"
        "var GTYPES=['net','chginv'];"
        "var mode=0,dmp=0,tpa=100,tpm=100,texp=20,dthr=60,divUser=0,divOn=0,macSet=false,inv2On=false,bmsMAC='',bms2MAC='',inv2IP='',bypIP='',boostWh=10,mips=['','','','','',''];"
        "var DAYS=['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'];"
        "var MOS=['January','February','March','April','May','June','July','August','September','October','November','December'];"
        "var gf=document.getElementById('gaugeFill');"
        "var CIRC=2*Math.PI*90;"
        "if(gf){gf.style.strokeDasharray=CIRC;gf.style.strokeDashoffset=CIRC;}"
        "function setV(id,v){var e=document.getElementById(id);if(e){if(e.tagName==='INPUT')e.value=v;else e.innerHTML=v;}}"
        "function setS(id,v){var e=document.getElementById(id);if(e)e.style.color=v;}"
        "function setCls(id,on,base){var e=document.getElementById(id);if(e)e.className=base+(on?' on':'');}"
        "function show(id,on){var e=document.getElementById(id);if(e)e.className=on?'tmr show':'tmr';}"
        "function _b64toBytes(s){var bin=atob(s),len=bin.length,out=new Uint8Array(len),i;for(i=0;i<len;i++)out[i]=bin.charCodeAt(i);return out;}"
        "function _u16(b,o){return b[o]|(b[o+1]<<8);}"
        "function _u32(b,o){return (b[o]|(b[o+1]<<8)|(b[o+2]<<16)|(b[o+3]<<24))>>>0;}"
        "function _s16(b,o){var v=_u16(b,o);return v&0x8000?v-0x10000:v;}"
        "function _k2(v){return (v/100).toFixed(2);}"
        "function xhr(url,cb){var r=new XMLHttpRequest();var done=false;"
        "function finish(v){if(done)return;done=true;clearTimeout(tmr);try{r.abort();}catch(e){}cb(v);}"
        "var tmr=setTimeout(function(){finish(null);},8000);"
        "r.onreadystatechange=function(){if(r.readyState!==4)return;try{finish(r.status===200?JSON.parse(r.responseText):null);}catch(e){finish(null);}};"
        "r.onerror=function(){finish(null);};"
        "r.open('GET',url+'&t='+Date.now(),true);r.send();}"
    );
    rtos_delay_milliseconds(1);

    // --- JS part 2: control handlers ---
    poststr(request,
        // pending-confirm guard: after a click/drag we hold the local value and
        // ignore polled values for that control until the device echoes the
        // expected value (or the deadline passes). Stops stale in-flight polls
        // from snapping buttons/sliders back. Commands re-fetch core on completion.
        "var pend={};"
        "function mark(k,v){pend[k]={v:v,t:Date.now()+9000};}"
        "function held(k){var p=pend[k];return !!(p&&Date.now()<p.t);}"
        "function rec(k,dev,loc){var p=pend[k];if(!p)return dev;if(Date.now()>=p.t){delete pend[k];return dev;}if(dev===p.v){delete pend[k];return dev;}return loc;}"
        "function clrIf(k,dev){var p=pend[k];if(p&&dev===p.v)delete pend[k];}"
        "function cmd(u,k,v){if(k!==null)mark(k,v);xhr(u,function(){xhr('/api_dash?req=core',function(d){if(d&&d.c)applyCore(d);});});}"
        "function toggleCfg(){var p=document.getElementById('cfg-pop');if(p)p.style.display=(p.style.display==='none')?'block':'none';}"
        "function toggleBatCfg(){var p=document.getElementById('bat-pop');if(p)p.style.display=(p.style.display==='none')?'block':'none';}"
        "var cutCV=400,cutIV=330;"
        "function bvIn(k,v){var n=parseInt(v,10);if(k==='cv'){cutCV=n;setV('lbl-cv',(n/100).toFixed(2));}else{cutIV=n;setV('lbl-iv',(n/100).toFixed(2));}}"
        "function s_cv(v){cutCV=parseInt(v,10);setV('lbl-cv',(cutCV/100).toFixed(2));cmd('/cm?cmnd=SetChargerCutoff%20'+v,null,0);}"
        "function s_iv(v){cutIV=parseInt(v,10);setV('lbl-iv',(cutIV/100).toFixed(2));cmd('/cm?cmnd=SetInverterCutoff%20'+v,null,0);}"
        "function refreshSliders(){"
        "var mp=(mode===0)?tpa:tpm;if(!held('pwr')){setV('lbl-pwr',mp);if(mp>=18)setV('sld-pwr',mp);}"
        "if(!held('exp')){setV('lbl-exp',texp);setV('sld-exp',texp);}}"
        "function fmtMac(el){var raw=el.value.replace(/[^0-9a-fA-F]/g,'').slice(0,12).toUpperCase();var out='';for(var i=0;i<raw.length;i++){if(i>0&&i%2===0)out+=':';out+=raw[i];}el.value=out;}"
        "function loadCfg(){try{var ls=localStorage;"
        "var m=ls.getItem('bmsMAC');if(m){bmsMAC=m;setV('bms1-mac',m);}"
        "var m2=ls.getItem('bms2MAC');if(m2){bms2MAC=m2;setV('bms2-mac',m2);}"
        "var i2=ls.getItem('inv2IP');if(i2){inv2IP=i2;setV('inv2-ip',i2);}"
        "var by=ls.getItem('bypIP');if(by){bypIP=by;setV('byp-ip',by);}"
        "for(var n=1;n<=6;n++){var ip=ls.getItem('mip'+n);if(ip){mips[n-1]=ip;setV('m'+n+'-ip',ip);}}"
        "var bw=ls.getItem('boostWh');if(bw){boostWh=parseInt(bw,10);setV('sld-boost',bw);setV('lbl-boost',bw);}"
        "var cd=ls.getItem('cfgDthr');if(cd){dthr=parseInt(cd,10);setV('cfg-sld-div',cd);var el=document.getElementById('cfg-lbl-div');if(el)el.innerHTML='-'+cd;}"
        "}catch(e){}}"
        "function doCfgRetrieve(){var rb=document.getElementById('cfg-ret-btn');"
        "if(rb){rb.disabled=true;rb.innerHTML='Loading...';}loadCfg();"
        "xhr('/api_dash?req=cfg',function(d){if(d){"
        "var fs=['bms1-mac','bms2-mac','m1-ip','m2-ip','m3-ip','m4-ip','m5-ip','m6-ip','inv2-ip','byp-ip'];"
        "var ks=['bms1','bms2','m1','m2','m3','m4','m5','m6','inv2','byp'];"
        "for(var i=0;i<fs.length;i++)if(d[ks[i]])setV(fs[i],d[ks[i]]);"
        "if(d.boost){boostWh=d.boost;setV('sld-boost',d.boost);setV('lbl-boost',d.boost);}"
        "if(d.dthr){dthr=d.dthr;setV('cfg-sld-div',d.dthr);var el=document.getElementById('cfg-lbl-div');if(el)el.innerHTML='-'+d.dthr;}}"
        "if(rb){rb.disabled=false;rb.innerHTML='&#x21d3; Retrieve';}}); }"
        "function doCfgSave(){var get=function(id){var e=document.getElementById(id);return e?e.value:'';};"
        "bmsMAC=get('bms1-mac');bms2MAC=get('bms2-mac');inv2IP=get('inv2-ip');bypIP=get('byp-ip');"
        "boostWh=parseInt(get('sld-boost')||'10',10);"
        "dthr=parseInt(get('cfg-sld-div')||'60',10);"
        "try{var ls=localStorage;"
        "if(bmsMAC)ls.setItem('bmsMAC',bmsMAC);if(bms2MAC)ls.setItem('bms2MAC',bms2MAC);"
        "for(var n=1;n<=6;n++){var v=get('m'+n+'-ip');if(v){mips[n-1]=v;ls.setItem('mip'+n,v);}}"
        "if(inv2IP)ls.setItem('inv2IP',inv2IP);if(bypIP)ls.setItem('bypIP',bypIP);"
        "ls.setItem('boostWh',boostWh);ls.setItem('cfgDthr',dthr);}catch(e){}"
        "if(bmsMAC)cmd('/cm?cmnd=SetBmsMAC%20'+encodeURIComponent(bmsMAC),null,0);"
        "if(bms2MAC)cmd('/cm?cmnd=SetBms2MAC%20'+encodeURIComponent(bms2MAC),null,0);"
        "for(var n=1;n<=6;n++){var v=get('m'+n+'-ip');if(v)cmd('/cm?cmnd=SetMeterIP%20'+n+'%20'+v,null,0);}"
        "if(inv2IP)cmd('/cm?cmnd=SetInv2IP%20'+inv2IP,null,0);"
        "if(bypIP)cmd('/cm?cmnd=SetBypassIP%20'+bypIP,null,0);"
        "cmd('/cm?cmnd=SetBoostPower%20'+boostWh,null,0);"
        "cmd('/cm?cmnd=SetDivertThreshold%20'+dthr,null,0);"
        "var sb=document.getElementById('cfg-sv-btn');"
        "if(sb){sb.innerHTML='Saved &#x2713;';setTimeout(function(){sb.innerHTML='Save';},2000);}}"
        "function sIn(k,v){mark(k,parseInt(v,10));if(k==='pwr')setV('lbl-pwr',v);else if(k==='exp')setV('lbl-exp',v);}"
        "function s_pwr(v){var iv=parseInt(v,10);if(mode===0)tpa=iv;else tpm=iv;mark('pwr',iv);cmd('/cm?cmnd=SetTargetPower%20'+v,null,0);setV('lbl-pwr',v);}"
        "function s_exp(v){texp=parseInt(v,10);mark('exp',texp);cmd('/cm?cmnd=SetTargetExport%20'+v,null,0);setV('lbl-exp',v);}"
        "var IC_AUTO=\"<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2' stroke-linecap='round' stroke-linejoin='round'><path d='M23 4v6h-6'/><path d='M1 20v-6h6'/><path d='M3.51 9a9 9 0 0 1 14.85-3.36L23 10'/><path d='M1 14l4.64 4.36A9 9 0 0 0 20.49 15'/></svg>\";"
        "var IC_CLOCK=\"<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='9'/><path d='M12 7v5l3 2'/></svg>\";"
        "var IC_LOCK=\"<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='11' width='18' height='11' rx='2'/><path d='M7 11V7a5 5 0 0 1 10 0v4'/></svg>\";"
        "function btnColor(){"
        "setV('m-ic',mode===0?IC_AUTO:(mode===1?IC_CLOCK:IC_LOCK));"
        "setV('m-txt',mode===0?'AUTO':'MANUAL');"
        "var mb=document.getElementById('m-btn');"
        "if(mb)mb.style.background=mode===0?'#09F':(mode===1?'#8e44ad':'#f44336');"
        "var i=document.getElementById('inv1-btn'),i2=document.getElementById('inv2-btn'),c=document.getElementById('chg-btn');"
        "if(i)i.style.background=(dmp===5)?'#ff9800':'#555';"
        "if(i2)i2.style.background=inv2On?'#4caf50':'#555';"
        "if(c)c.style.background=(dmp>18)?'#4caf50':((dmp>=10&&dmp<=18)?'#8bc34a':'#555');"
        "var db=document.getElementById('div-btn');"
        "setV('div-ic',divUser===0?IC_AUTO:(divUser===1?IC_CLOCK:IC_LOCK));"
        "if(db)db.style.background=(divUser===1)?'#8e44ad':((divUser===2)?'#f44336':(divOn?'#ff9800':'#555'));}"
        "function tm(){mode=(mode+1)%3;cmd('/cm?cmnd=SetChargerMode%20'+mode,'mode',mode);btnColor();refreshSliders();}"
        "function td(){divUser=(divUser+1)%3;cmd('/cm?cmnd=SetDivertUser%20'+divUser,'divu',divUser);btnColor();}"
        "function setDump(v){dmp=v;cmd('/cm?cmnd=SetDumpLoad%20'+v,'dmp',v);btnColor();}"
        "function t_inv1(){if(mode===0)return;setDump(dmp===5?0:5);}"
        "function t_inv2(){inv2On=!inv2On;if(inv2IP)cmd('/cm?cmnd=SetInv2%20'+(inv2On?1:0),null,0);btnColor();}"
        "function t_chg(){if(mode===0)return;setDump(dmp>=18?0:18);}"
        "function toggleSnsCfg(){var p=document.getElementById('sns-pop');if(p)p.style.display=(p.style.display==='none')?'block':'none';}"


    );
    rtos_delay_milliseconds(1);

    // --- JS part 3: applyCore ---
    poststr(request,
        "function applyCore(d){"
        "var b=_b64toBytes(d.c);"
        "var volt=_u16(b,0)/10,curr=_u16(b,2)/100,pwr=_s16(b,4),cpwr=_s16(b,6),bal=_s16(b,8),est=_s16(b,10);"
        "dmp=rec('dmp',b[12],dmp);mode=rec('mode',b[13],mode);"
        "var dTpa=b[14],dTexp=b[15];"
        "var clk_h=b[16],clk_m=b[17];var ev=_u16(b,20);var flags=b[22];var dTpm=b[23];divUser=rec('divu',b[24],divUser);var dDthr=b[25];"
        "clrIf('pwr',(mode===0)?dTpa:dTpm);clrIf('exp',dTexp);clrIf('div',dDthr);"
        "if(!held('pwr')){tpa=dTpa;tpm=dTpm;}if(!held('exp')){texp=dTexp;}if(!held('div')){dthr=dDthr;}"
        "var hntp=flags&1;divOn=(flags&2)?1:0;"
        "setV('d-va',volt.toFixed(0)+'V / '+curr.toFixed(2)+'A');"
        "var pe=document.getElementById('d-pwr');"
        "if(pe)pe.innerHTML='<span class=\"'+(pwr<0?'c-exp':'c-imp')+'\">'+pwr+' W</span> / <span class=\"'+(cpwr<0?'c-exp':'c-imp')+'\">'+cpwr+' W</span>';"
        "setV('d-bal',bal+' Wh');setS('d-bal',bal<0?'#4caf50':'#f44336');"
        "setV('d-est',est+' Wh');setS('d-est',est<0?'#4caf50':'#f44336');"
        "var cv,cc;if(dmp===0){cv='Idle';cc='#888';}else if(dmp===5){cv='Battery';cc='#4caf50';}else{cv=dmp+'%';cc='#0099FF';}"
        "setV('c-v',cv);setS('c-v',cc);"
        "setV('c-chg',(dmp>=18&&dmp<=100)?'Charging':'');"
        "var cs=('0'+clk_h).slice(-2)+':'+('0'+clk_m).slice(-2);"
        "if(cs!==lastClk){setV('d-clk',cs);lastClk=cs;}"
        "var no=document.getElementById('night');if(no)no.style.opacity=(clk_h>=22||clk_h<6)?'0.5':'0';"
        "refreshSliders();btnColor();"
        "var dt=new Date();setV('d-day',DAYS[dt.getDay()]);setV('d-date',MOS[dt.getMonth()]+' '+dt.getDate()+', '+dt.getFullYear());"
        "return hntp?ev:null;}"
    );
    rtos_delay_milliseconds(1);

    // --- JS part 4: applyEnergy + applyBms ---
    poststr(request,
        "function applyEnergy(d){"
        "var b=_b64toBytes(d.e);"
        "setV('d-tot-i',_k2(_u32(b,0)));setV('d-tot-e',_k2(_u32(b,4)));"
        "setV('d-clh-i',_k2(_u16(b,8)));setV('d-ctoday-i',_k2(_u16(b,10)));setV('d-cyest-i',_k2(_u16(b,12)));setV('d-c2d-i',_k2(_u16(b,14)));setV('d-c3d-i',_k2(_u16(b,16)));"
        "setV('d-clh-e',_k2(_u16(b,18)));setV('d-ctoday-e',_k2(_u16(b,20)));setV('d-cyest-e',_k2(_u16(b,22)));setV('d-c2d-e',_k2(_u16(b,24)));setV('d-c3d-e',_k2(_u16(b,26)));"
        "lastEv=d.ev;lastEnergyT=Date.now();}"
        "function applyBms(d){"
        "if(!macSet&&d.mac){setV('bt-title','<svg width=\"11\" height=\"13\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#4aa3ff\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"margin-right:5px;vertical-align:middle\"><path d=\"m7 7 10 10-5 5V2l5 5L7 17\"/></svg>'+d.mac);macSet=true;"
        "var mi=document.getElementById('bms1-mac');if(mi&&!mi.value&&!bmsMAC){mi.value=d.mac.toUpperCase();bmsMAC=d.mac;}}"
        "if(!d.b)return;var b=_b64toBytes(d.b);var fl=b[0];"
        "if(!(fl&8)){setV('bt-state','offline');setS('bt-state','#7c8a9a');if(gf)gf.style.stroke='#3a4452';return;}"
        "var soc=b[1],volt=_u16(b,2)/100,curr=_s16(b,4)/100,rem=_u16(b,6)/10,full=_u16(b,8)/10;"
        "var cmin=_u16(b,10)/1000,cmax=_u16(b,12)/1000,t1=_s16(b,14)/10,t2=_s16(b,16)/10,tmos=_s16(b,18)/10,bcur=_s16(b,20)/100;"
        "var st=curr>0.05?'Charging':(curr<-0.05?'Discharging':'Idle');"
        "var s2=Math.max(0,Math.min(100,soc));"
        "var col=s2>60?'#37d67a':(s2>=30?'#e8a317':'#ef5350');"
        "if(gf){gf.style.strokeDashoffset=CIRC*(1-s2/100);gf.style.stroke=col;}"
        "setV('bt-pwr',Math.round(volt*curr));setV('bt-soc',soc);setS('bt-soc',col);setS('bt-pct',col);"
        "setV('bt-state',st);setS('bt-state',col);"
        "setV('bt-a',(curr>=0?'+':'')+curr.toFixed(2));setV('bt-v',volt.toFixed(2));"
        "setV('bt-cap',rem.toFixed(1));setV('bt-capf',full.toFixed(1));"
        "setV('bt-cells',cmin.toFixed(3)+' - '+cmax.toFixed(3));"
        "setV('bt-delta',Math.round((cmax-cmin)*1000));"
        "setV('bt-tbat',t1.toFixed(1)+' | '+t2.toFixed(1));setV('bt-tmos',tmos.toFixed(1));"
        "setV('bt-bal',bcur.toFixed(2));"
        "setCls('bt-chg',(fl&1),'cd-item');setCls('bt-dis',(fl&2)?1:0,'cd-item');"
        "setCls('bt-balrow',(fl&4)?1:0,'trow');}"
    );
    rtos_delay_milliseconds(1);

    // --- JS part 5: graph decode + poll cycle ---
    poststr(request,
        "function _decodeNet(d){if(!d.net)return;var b=_b64toBytes(d.net),n=b.length,i;state_import=new Array(n);state_export=new Array(n);for(i=0;i<n;i++){var v=b[i]*2-150;state_import[i]=v>0?v:0;state_export[i]=v<0?v:0;}}"
        "function _decodeChgInv(s){var b=_b64toBytes(s),n=b.length,i;var chg=new Array(n),inv=new Array(n);for(i=0;i<n;i++){var v=b[i];if(v&0x80)v-=0x100;chg[i]=v>0?v:0;inv[i]=v<0?-v:0;}return {chg:chg,inv:inv};}"
        "function applyGraph(d){_decodeNet(d);if(d.chginv){var ci=_decodeChgInv(d.chginv);state_chg=ci.chg;state_inv=ci.inv;}renderGraph();}"
        "function runCycle(){"
        "if(busy&&(Date.now()-busySince)<15000)return;busy=true;busySince=Date.now();var now=Date.now();"
        "xhr('/api_dash?req=core',function(d){"
        "var needEnergy=false;if(d&&d.c){var ev=applyCore(d);needEnergy=(ev!==null)&&(ev!==lastEv||now-lastEnergyT>=60000);}"
        "xhr('/api_dash?req=bms',function(bd){if(bd)applyBms(bd);"
        "function doGraph(){if(now-lastGraphT<20000){busy=false;return;}xhr('/api_dash?req='+GTYPES[graphIdx%2],function(gd){if(gd){applyGraph(gd);lastGraphT=Date.now();graphIdx++;}busy=false;});}"
        "if(needEnergy){xhr('/api_dash?req=energy',function(ed){if(ed)applyEnergy(ed);doGraph();});}else{doGraph();}"
        "});});}"
        "function loadAll(){busy=true;busySince=Date.now();"
        "xhr('/api_dash?req=core',function(d){if(d&&d.c)applyCore(d);"
        "xhr('/api_dash?req=energy',function(ed){if(ed)applyEnergy(ed);"
        "xhr('/api_dash?req=bms',function(bd){if(bd)applyBms(bd);"
        "xhr('/api_dash?req=net',function(g){if(g)applyGraph(g);"
        "xhr('/api_dash?req=chginv',function(g2){if(g2)applyGraph(g2);lastGraphT=Date.now();graphIdx=0;busy=false;});});});});});}"
        "</script>"
    );
    rtos_delay_milliseconds(1);

    // --- JS part 6: graph drawing + init/start (unchanged renderer) ---
    poststr(request,
        "<script>"
        "function _buildPath(ctx,p){ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);"
        "for(var i=0;i<47;i++){var xc=(p[i].x+p[i+1].x)/2,yc=(p[i].y+p[i+1].y)/2;ctx.quadraticCurveTo(p[i].x,p[i].y,xc,yc);}"
        "ctx.lineTo(p[47].x,p[47].y);}"
        "function drawSmooth(ctx,arr,baseY,clamp,fill,col,lw){if(!arr||arr.length===0)return;var p=[],h,i;"
        "for(i=0;i<48;i++){h=(arr[i]||0)/2;if(clamp){if(h>150)h=150;if(h<-75)h=-75;}p.push({x:i*11+60,y:baseY-h});}"
        "if(fill){_buildPath(ctx,p);ctx.lineTo(577,baseY);ctx.lineTo(60,baseY);ctx.fillStyle=fill;ctx.fill();}"
        "_buildPath(ctx,p);ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.stroke();"
        "ctx.beginPath();ctx.arc(p[47].x,p[47].y,lw*1.5,0,2*Math.PI);ctx.fillStyle=col;ctx.fill();}"
        "var gridCanvas=null;"
        "function initGrid(){var gc=document.createElement('canvas');var r=window.devicePixelRatio||1;"
        "gc.width=Math.round(592*r);gc.height=Math.round(340*r);var ctx=gc.getContext('2d');ctx.scale(r,r);"
        "ctx.fillStyle='#181818';ctx.fillRect(60,10,517,50);ctx.fillRect(60,75,517,235);"
        "ctx.lineWidth=1;ctx.strokeStyle='#333';ctx.beginPath();"
        "ctx.moveTo(60,35);ctx.lineTo(577,35);ctx.moveTo(60,75);ctx.lineTo(577,75);ctx.moveTo(60,150);ctx.lineTo(577,150);ctx.moveTo(60,300);ctx.lineTo(577,300);ctx.stroke();"
        "ctx.strokeStyle='#444';ctx.beginPath();ctx.moveTo(60,60);ctx.lineTo(577,60);ctx.moveTo(60,225);ctx.lineTo(577,225);ctx.stroke();"
        "ctx.strokeStyle='#666';ctx.beginPath();ctx.moveTo(60,10);ctx.lineTo(60,60);ctx.moveTo(60,75);ctx.lineTo(60,310);ctx.moveTo(577,10);ctx.lineTo(577,60);ctx.moveTo(577,75);ctx.lineTo(577,310);ctx.stroke();"
        "ctx.fillStyle='#aaa';ctx.font='14px sans-serif';ctx.textAlign='right';ctx.textBaseline='middle';"
        "ctx.fillText('100',48,10);ctx.fillText('0',48,60);ctx.fillText('+300',48,75);ctx.fillText('+150',48,150);"
        "ctx.fillStyle='#ccc';ctx.fillText('0 Wh',48,225);ctx.fillStyle='#aaa';ctx.fillText('-150',48,300);"
        "ctx.lineWidth=1;ctx.beginPath();ctx.font='12px sans-serif';ctx.textBaseline='top';"
        "for(var i=0;i<=47;i++){var x=(47-i)*11+60;ctx.moveTo(x,310);if(i%4===0){ctx.lineTo(x,316);ctx.textAlign=(i===0)?'right':'center';ctx.fillText((i===0)?'Now':'-'+(i/4)+'h',x,320);}else{ctx.lineTo(x,313);}}"
        "ctx.stroke();gridCanvas=gc;}"
        "function renderGraph(){var c=document.getElementById('dynCanvas');if(!c||!c.getContext)return;var ctx=c.getContext('2d');var r=window.devicePixelRatio||1;"
        "c.width=Math.round(592*r);c.height=Math.round(340*r);ctx.scale(r,r);ctx.clearRect(0,0,592,340);if(gridCanvas)ctx.drawImage(gridCanvas,0,0,592,340);"
        "if(state_import.length>0){var gi=ctx.createLinearGradient(0,75,0,225);gi.addColorStop(0,'rgba(244,67,54,.5)');gi.addColorStop(1,'rgba(244,67,54,.05)');drawSmooth(ctx,state_import,225,true,gi,'#ef5350',2.5);}"
        "if(state_export.length>0){var ge=ctx.createLinearGradient(0,225,0,310);ge.addColorStop(0,'rgba(55,214,122,.05)');ge.addColorStop(1,'rgba(55,214,122,.5)');drawSmooth(ctx,state_export,225,true,ge,'#37d67a',2.5);}"
        "if(state_chg.length>0)drawSmooth(ctx,state_chg,60,false,null,'#4caf50',2.5);"
        "if(state_inv.length>0)drawSmooth(ctx,state_inv,60,false,null,'#ff9800',2.5);}"
        "function fit(){var c=document.getElementById('dash-container');if(!c)return;"
        "var bp=document.getElementById('batt-panel'),gc=document.getElementById('graph-col'),lg=document.getElementById('leg-h');"
        "if(bp&&gc&&lg){var gh=bp.offsetHeight-lg.offsetHeight-10;if(gh<150)gh=150;gc.style.height=gh+'px';}"
        "var w=c.offsetWidth||980,h=c.offsetHeight||700;var s=Math.min(window.innerWidth/w,window.innerHeight/h,1);var e=document.getElementById('scaler');var t='translate(-50%,-50%) scale('+s+')';e.style.webkitTransform=t;e.style.transform=t;}"
        "function fixBtns(){var bs=document.querySelectorAll('.btn'),i,b,bh,ch,j,nd,p;"
        "for(i=0;i<bs.length;i++){b=bs[i];b.style.paddingTop='0';b.style.paddingBottom='0';}"
        "for(i=0;i<bs.length;i++){b=bs[i];"
        "if(b.className.indexOf('btn-div')!==-1)continue;"
        "bh=b.clientHeight;ch=0;"
        "for(j=0;j<b.childNodes.length;j++){nd=b.childNodes[j];if(nd.nodeType===1)ch+=nd.offsetHeight||0;}"
        "if(bh>ch+2){p=Math.floor((bh-ch)/2)+'px';b.style.paddingTop=p;b.style.paddingBottom=p;}}"
        "initGrid();loadAll();setInterval(runCycle,10000);fit();fixBtns();btnColor();loadCfg();window.onresize=function(){fit();fixBtns();};setTimeout(function(){fit();fixBtns();},350);"
        "</script></body></html>"
    );
    rtos_delay_milliseconds(1);

    poststr(request, NULL);
    return 0;
}
