name: Build App
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP_NAME: ${{ github.event.repository.name }}

jobs:
  refs:
    name: Prepare CI Environment
    runs-on: ubuntu-22.04
    outputs:
      sha_short: ${{ steps.refs.outputs.sha_short }}
      short_ref: ${{ steps.refs.outputs.short_ref }}
      version: ${{ steps.refs.outputs.version }}
      new_release: ${{ steps.refs.outputs.new_release }}
    steps:
      - name: Source checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        id: semantic
        if: github.ref == 'refs/heads/main' || github.ref_name == 'alpha'
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          semantic_version: 21
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits@7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: refs
        run: |
          export BRANCH=${GITHUB_REF#refs/*/}
          export BRANCHTRANSLATED=$(echo ${BRANCH} | tr '/' '_')
          export VERSION=""
          if ${{ steps.semantic.outputs.new_release_published == 'true' }}; then
            export VERSION=${{ steps.semantic.outputs.new_release_version }}
          else
            export VERSION=${BRANCHTRANSLATED}_$(git rev-parse --short=12 HEAD)
          fi
          echo "new_release=${{ steps.semantic.outputs.new_release_published }}" >> $GITHUB_OUTPUT
          echo "short_ref=${BRANCHTRANSLATED}" >> $GITHUB_OUTPUT
          echo "sha_short=SHA-$(git rev-parse --short=12 HEAD)" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build_esp32:
    name: Build ESP32-C3 (BLE + WiFi)
    needs: refs
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: OpenESP32C3
            variant: 4M
            version: v5.5.2
            sdk: esp-idf

    steps:
      - name: Source checkout
        uses: actions/checkout@v4

      - name: ESP-IDF checkout
        uses: actions/checkout@v4
        with:
          repository: espressif/esp-idf
          path: sdk/esp-idf
          ref: ${{ matrix.version }}
          submodules: recursive

      - uses: actions/setup-python@v5
        id: pysetup
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake
          version: 1.0

      - name: Cache ESP-IDF toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: ~/.espressif
          key: ${{ matrix.sdk }}_toolchain_${{ matrix.version }}_${{ steps.pysetup.outputs.python-version }}

      - name: Get toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          cd sdk/${{ matrix.sdk }}
          ./install.sh

      - name: Run make
        run: |
          cd sdk/${{ matrix.sdk }}
          . ./export.sh
          . ./add_path.sh
          cd ../..
          make APP_VERSION=${{ needs.refs.outputs.version }}_${{ matrix.variant }} APP_NAME=${{ matrix.platform }} VARIANT="${{ matrix.variant }}" ${{ matrix.platform }}

      - name: Save build assets
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}_${{ needs.refs.outputs.version }}_${{ matrix.platform }}_${{ matrix.variant }}
          path: |
            output/${{ needs.refs.outputs.version }}_${{ matrix.variant }}/${{ matrix.platform }}_${{ needs.refs.outputs.version }}_${{ matrix.variant }}.img
            output/${{ needs.refs.outputs.version }}_${{ matrix.variant }}/${{ matrix.platform }}_${{ needs.refs.outputs.version }}_${{ matrix.variant }}.factory.bin
            output/${{ needs.refs.outputs.version }}_${{ matrix.variant }}/${{ matrix.platform }}_2MB_${{ needs.refs.outputs.version }}_${{ matrix.variant }}.factory.bin
          if-no-files-found: warn

  release:
    name: Semantic Release
    runs-on: ubuntu-22.04
    needs: [refs, build_esp32]
    if: always() && needs.refs.outputs.new_release == 'true' && (github.ref == 'refs/heads/main' || github.ref_name == 'alpha')
    steps:
      - name: Source checkout
        uses: actions/checkout@v4
      - name: Fetch build assets
        uses: actions/download-artifact@v4
        with:
          path: output/${{ needs.refs.outputs.version }}
          merge-multiple: true
      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: false
          semantic_version: 21
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits@7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
